CREATE TABLE JOBCOMPATIBILITY (
	
    IDJOBCOMPATIBILITY INT(11) NOT NULL AUTO_INCREMENT,
	IDJOB INT(11) NOT NULL,
	IDUSER INT(11) NOT NULL,
	SCORE INT(11) NOT NULL,
	MAXSCORE INT(11) NOT NULL,
    PRIMARY KEY (IDJOBCOMPATIBILITY),
	UNIQUE (IDJOB, IDUSER),
    FOREIGN KEY (IDJOB) REFERENCES job(IDJOB),
    FOREIGN KEY (IDUSER) REFERENCES user(IDUSER)
)